version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx-server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - app-dev
    networks:
      - power-dashboard-network

  # Single PostgreSQL with multiple databases
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - power-dashboard-network

  # Single Redis with multiple database numbers
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - power-dashboard-network

  # Single RabbitMQ with multiple vhosts
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - power-dashboard-network

  app:
    build:
      context: .
      dockerfile: infra/Dockerfile.app.prod
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

  app-dev:
    build:
      context: .
      dockerfile: infra/Dockerfile.app.dev
    container_name: app-dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

  queue-worker:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: queue-worker
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

  scheduler:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan schedule:work
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

  queue-worker-dev:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: queue-worker-dev
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

  scheduler-dev:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: scheduler-dev
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan schedule:work
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - power-dashboard-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  power-dashboard-network:
    driver: host
