services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - apps/frontend:/app:cached
    command: ["pnpm", "start"]
    ports:
      - "3000:3000"
    networks:
      - pd-public
      - pd-private

  backend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - apps/backend:/app:cached
    command: ["pnpm", "serve"]
    ports:
      - "4000:4000"
    networks:
      - pd-private

  cms:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - apps/cms:/app:cached
    command: ["pnpm", "admin"]
    ports:
      - "1337:1337"
    networks:
      - pd-private

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: powerdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pd-private

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adm.in
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pd-public
      - pd-private

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - pd-public
  #     - pd-private

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - pd-public
  #     - pd-private

volumes:
  pgdata:

networks:
  pd-private:
    driver: bridge
  pd-public:
    driver: bridge
