apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: power-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: your-cms-image:latest
        ports:
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: cms
  namespace: power-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 1337
    targetPort: 1337
  selector:
    app: cms

