name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        timeout: 300s
        command_timeout: 60m
        script: |
          # Navigate to project directory
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Create backup of current deployment
          if [ -d "backup" ]; then
            rm -rf backup
          fi
          mkdir -p backup
          cp -r . backup/ 2>/dev/null || true
          
          # Pull latest code
          git pull origin main
          
          # Generate complete .env file from secrets
          cat > .env << EOF
          APP_NAME=PowerDashboard
          APP_ENV=production
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_URL=${{ secrets.APP_URL }}

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=error

          DB_CONNECTION=pgsql
          DB_HOST=power-dashboard-postgres
          DB_PORT=5432
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=pusher
          CACHE_DRIVER=redis
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=redis
          SESSION_DRIVER=redis
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1

          REDIS_HOST=power-dashboard-redis
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT=6379

          RABBITMQ_HOST=power-dashboard-rabbitmq
          RABBITMQ_PORT=5672
          RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_VHOST=/

          MAIL_MAILER=smtp
          MAIL_HOST=mailpit
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="noreply@${{ secrets.APP_URL }}"
          MAIL_FROM_NAME="PowerDashboard"

          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_HOST=
          PUSHER_PORT=443
          PUSHER_SCHEME=https
          PUSHER_APP_CLUSTER=mt1

          VITE_PUSHER_APP_KEY=
          VITE_PUSHER_HOST=
          VITE_PUSHER_PORT=443
          VITE_PUSHER_SCHEME=https
          VITE_PUSHER_APP_CLUSTER=mt1

          SANCTUM_STATEFUL_DOMAINS=${{ secrets.APP_URL }},localhost,127.0.0.1,127.0.0.1:8000,::1
          EOF
          
          # Stop current containers
          docker compose -f infra/docker-compose.yml down
          
          # Build and start new containers
          docker compose -f infra/docker-compose.yml up -d --build
          
          # Wait for services to be ready
          sleep 30
          
          # Deployment completed successfully
          echo "Deployment successful!"
          # Clean up backup
          rm -rf backup
